# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 12:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=10)),
                ('long', models.CharField(max_length=10)),
                ('system_capacity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LiveDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('daily_dc', django.contrib.postgres.fields.jsonb.JSONField()),
                ('installation_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarsys.InstallationKey')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('daily_dc', django.contrib.postgres.fields.jsonb.JSONField()),
                ('installation_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarsys.InstallationKey')),
            ],
        ),
    ]
