# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarsys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencedc',
            old_name='date',
            new_name='date_loaded',
        ),
    ]
