# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarsys', '0002_installationkey_livedc_referencedc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDCDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=10)),
                ('long', models.CharField(max_length=10)),
                ('system_capacity', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('dc_power', models.CharField(max_length=200)),
            ],
        ),
    ]
