# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarsys', '0003_livedcdump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationkey',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='installationkey',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='installationkey',
            name='system_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='livedcdump',
            name='dc_power',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='livedcdump',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='livedcdump',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='livedcdump',
            name='system_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
