# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarsys', '0004_auto_20170221_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livedcdump',
            old_name='date',
            new_name='timestamp',
        ),
    ]
