# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarsys', '0007_auto_20170221_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationkey',
            name='system_capacity',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='livedcdump',
            name='system_capacity',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
